Fix metadata storing, add a 'force download' option, and some docs
TheFox/flickr-cli pull request #11
Opened 2016-12-07 09:40 UTC by samwilson

This updates some documentation, refactors the base execute() method
of the Download command, fixes the URL of the original file that's
downloaded, prevents display of a progress bar if we don't know the
full size of the photo, avoids the non-existant fileNameCountup()
function, and introduces a new 'force' option that will re-download
a photo even if it already exists locally.

Refs #10

2016-12-07 20:21 UTC, TheFox requested changes
I got many of these notices:

```
Notice: Trying to get property of non-object in src/TheFox/FlickrCli/Command/DownloadCommand.php on line 570
```

for `$info`.

The creation of an new array with `[]` is [not compitible with PHP 5.3](https://secure.php.net/manual/en/language.types.array.php). Either we change the required PHP version in composer.json or the array syntax.

2016-12-08 00:29 UTC, samwilson commented
PHP 5.3 [has been](https://secure.php.net/supported-versions.php) end-of-life for more than two years. I'd be in favour of updating the requirement to `~5.6 || ~7.0`; what do you think? Or maybe just 5.5?

I've hopefully fixed the undefined object errors (by returning early, and not saving metadata).

2016-12-08 12:08 UTC, TheFox commented
So it's better if we upgrade from 5.3 to 5.4?

2016-12-09 00:07 UTC, TheFox approved these changes

2016-12-09 00:07 UTC, merged

2016-12-09 02:47 UTC, samwilson commented
5.4 and 5.5 are both end-of-life already. So I think going for 5.6 as a minimum makes most sense. This tool is aimed at the sort of people who are probably running more up to date versions (i.e. not ancient shared hosting environments etc.).

2016-12-09 11:19 UTC, TheFox commented
I see.