Ask user to select required permission for authorisation
TheFox/flickr-cli pull request #8
Opened 2016-11-28 08:45 UTC by samwilson

This change adds a user prompt to select 'read', 'write', or
'delete' when they're retrieving the Access Token.

It also switches to using the SymphonyStyle class for console
input and output, as this gives us a few easy to use methods
and so reduces complexity in this class.

The config file path is also changed to be an absolute path,
both for the default and when it's supplied with the --config
CLI option, because there were errors when running from a
location outside of the base directory.

Refs: #7

2016-11-28 19:23 UTC, TheFox requested changes
Thank you for using this tool and for your contributions.

In general using `realpath` is a good idea, but consider this, from the [PHP documentation](https://secure.php.net/manual/en/function.realpath.php):

	realpath() returns FALSE on failure, e.g. if the file does not exist.

So `$configPath` is a boolean in my case.

Beside that fact, `__DIR__.'/../../../../config.yml'` was not a good idea at all. Consider this:  

	cd /tmp
	php ~/flickr-cli/application.php auth -c my_test.yml

The user expect that `my_test.yml` will be created at the current working directory (`/tmp/my_test.yml`). This should be the same behavior without `-c`:

	cd /tmp
	php ~/flickr-cli/application.php auth

The user expect that the default `config.yml` will be created at `/tmp/config.yml`, not at `~/flickr-cli/config.yml`. The paths should always be relative to the current working directory of the user. Please let `$configPath` untouched.

Maybe we can use [SplFileInfo](https://secure.php.net/manual/de/class.splfileinfo.php) or [webmozart/path-util](https://packagist.org/packages/webmozart/path-util) (didn't tested it yet) to handle paths.

I like `SymfonyStyle`. Didn't know that before.

2016-11-28 23:58 UTC, samwilson commented
Good point! I was not thinking properly.

I've updated the code.

2016-11-29 12:21 UTC, TheFox approved these changes

2016-11-29 12:21 UTC, merged

2016-11-29 12:22 UTC, TheFox commented
Nice! Thank you.